name: GraalVM Native Build

on:
  push:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup GraalVM for JDK 21
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'  # Ensure you're using GraalVM for Java 21
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Windows Native Image
        run: mvn clean package

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup GraalVM for JDK 21 (macOS)
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build macOS Native Image
        run: ./mvnw gluonfx:build

      - name: Wait for .app folder
        run: |
          for i in {1..30}; do
            if ls target/*.app >/dev/null 2>&1; then
              echo ".app folder found"
              break
            fi
            echo "Waiting for .app folder..."
            sleep 2
          done

      - name: Make script executable
        run: chmod +x ./package-dmg.sh

      - name: Run DMG creation script
        run: sh ./package-dmg.sh

      - name: Upload DMG artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-dmg
          path: target/*.dmg