name: Cross-Platform Native Build

on:
  push:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Visual Studio shell
        uses: egor-tensin/vs-shell@v1

      - name: Download GraalVM
        run: |
          curl -L https://github.com/graalvm/graalvm-ce-builds/releases/download/v23.1.2/graalvm-ce-java21-linux-amd64-23.1.2.tar.gz -o graalvm.tar.gz
          tar -xvzf graalvm.tar.gz
          sudo mv graalvm-ce-java21-23.1.2 /opt/graalvm

      - name: Set GraalVM environment variables
        run: |
          echo "GRAALVM_HOME=/opt/graalvm" >> $GITHUB_ENV
          echo "$GRAALVM_HOME/bin" >> $GITHUB_PATH

      - name: Build (Windows)
        shell: cmd
        run: .\mvnw gluonfx:build

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download GraalVM
        run: |
          curl -L https://github.com/graalvm/graalvm-ce-builds/releases/download/v23.1.2/graalvm-ce-java21-darwin-aarch64-23.1.2.tar.gz -o graalvm.tar.gz
          tar -xvzf graalvm.tar.gz
          sudo mv graalvm-ce-java21-23.1.2 /opt/graalvm

      - name: Set GraalVM environment variables
        run: |
          echo "GRAALVM_HOME=/opt/graalvm" >> $GITHUB_ENV
          echo "$GRAALVM_HOME/bin" >> $GITHUB_PATH

      - name: Build (macOS)
        run: ./mvnw gluonfx:build

      - name: Create DMG
        run: ./package-dmg.sh