name: Native Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up GraalVM JDK 21
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: 'maven'

      - name: Verify Java
        run: java -version

      - name: Set up Microsoft Build Tools (Windows only)
        if: runner.os == 'Windows'
        run: |
          choco install visualstudio2022buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.VCTools" --ignore-checksums -y

      - name: Add Visual Studio tools to PATH
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          for /f "delims=" %%i in ('dir /b /ad "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC"') do set "MSVC_VERSION=%%i"
          set "MSVC_PATH=C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\%MSVC_VERSION%\bin\Hostx64\x64"
          echo MSVC_PATH=%MSVC_PATH%
          echo PATH=%MSVC_PATH%;%PATH%
          echo "PATH=%MSVC_PATH%;%PATH%" >> %GITHUB_ENV%

      - name: Verify compiler availability
        if: runner.os == 'Windows'
        run: |
          echo %PATH%
          where cl || echo "Compiler not found in PATH"

      - name: Build native image
        run: mvn gluonfx:build