name: GraalVM Native Build

on:
  push:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup GraalVM for JDK 21
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'  # Ensure you're using GraalVM for Java 21
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Windows Native Image
        run: mvn clean package

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup GraalVM for JDK 21 (macOS)
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build macOS Native Image
        run: mvn clean package

      - name: Create DMG (macOS)
        run: ./package-dmg.sh