name: Build Electron Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      # This will continue to run other platforms even if one fails
      fail-fast: false
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          # Disable caching since lock file may not be available
          
      - name: Install dependencies
        # Use install instead of ci since lock file may not be available
        run: npm install
          
      - name: Build application
        run: npm run build
          
      # Set environment variables for the entire job using the env context at the job level
      # instead of as a separate step
      
      - name: Package application (Windows)
        if: matrix.os == 'windows-latest'
        run: npm run package-win
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        
      - name: Package application (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          # Build .app files for both architectures
          npm run package-mac
          
          # Debug - show directory contents after build
          echo "=== Contents of dist directory ==="
          ls -la dist/ || echo "dist directory not found"
          
          echo "=== All directories in dist ==="
          find dist -type d | sort
          
          echo "=== All .app files/directories ==="
          find dist -name "*.app" -type d | sort
          
          # Remove quarantine attributes to bypass Gatekeeper
          echo "=== Removing quarantine attributes from all .app bundles ==="
          sudo xattr -cr dist/**/*.app 2>/dev/null || echo "No .app files found with wildcards"
          sudo xattr -cr dist/*.app 2>/dev/null || echo "No .app files found directly in dist"
          sudo xattr -cr dist/*/*.app 2>/dev/null || echo "No .app files found in subdirectories"
          
          # More debug info
          echo "== Final directory structure of dist: =="
          ls -R dist/ || echo "No dist directory"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          
      # Upload macOS x64 artifact
      - name: Upload macOS x64 artifact
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: "BlitzLauncher-macos"
          path: |
            dist/**/*.app
            dist/*.app
          if-no-files-found: warn
          
      - name: Package application (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: npm run package-linux
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          
      # Upload artifacts for Windows and Linux
      - name: Upload Windows and Linux artifacts
        if: matrix.os != 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: "BlitzLauncher-${{ matrix.os }}.${{ matrix.os == 'windows-latest' && 'exe' || 'AppImage' }}"
          path: |
            dist/*.exe
            dist/*.AppImage
            dist/*.deb
          if-no-files-found: warn 