name: Build Electron Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'package.json'
          
      - name: Install dependencies
        run: |
          npm ci
          
      - name: Build application
        run: |
          npm run build
          
      - name: Package application (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          npm run package-win
        
      - name: Package application (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          npm run package-mac
          
      - name: Package application (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          npm run package-linux
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: BlitzLauncher-${{ matrix.os }}
          path: |
            dist/*.exe
            dist/*.dmg
            dist/*.AppImage
            dist/*.snap 