name: Build Electron Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      # This will continue to run other platforms even if one fails
      fail-fast: false
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          # Disable caching since lock file may not be available
          
      - name: Install dependencies
        # Use install instead of ci since lock file may not be available
        run: npm install
          
      - name: Build application
        run: npm run build
          
      # Set environment variables for the entire job using the env context at the job level
      # instead of as a separate step
      
      - name: Package application (Windows)
        if: matrix.os == 'windows-latest'
        run: npm run package-win
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        
      - name: Package application (macOS)
        if: matrix.os == 'macos-latest'
        run: npm run package-mac
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          
      - name: Package application (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: npm run package-linux
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: BlitzLauncher-${{ matrix.os }}
          path: |
            dist/*.exe
            dist/*.dmg
            dist/*.AppImage
            dist/*.snap
            dist/*.deb
          if-no-files-found: warn 