name: Build cx_Freeze Executables

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install cx-Freeze

      - name: Compile with cx_Freeze
        run: cxfreeze --script launch.py --target-dir dist

      - name: Compress for Linux/macOS
        if: runner.os != 'Windows'
        run: |
          zip -r ${{ runner.os == 'Linux' && 'linux-x64.zip' || 'macos-arm64.zip' }} dist/launch dist/lib

      - name: Compress for Windows
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          Compress-Archive -Path dist\launch, dist\lib -DestinationPath windows-x64.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os == 'macOS' && 'macos-arm64' || (runner.os == 'Windows' && 'windows-x64' || 'linux-x64') }}
          path: |
            release/*.zip