name: Build PyInstaller Executables

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Install minecraft-launcher-lib
        run: pip install minecraft-launcher-lib==7.1

      - name: Build executable with PyInstaller
        run: pyinstaller -y --onefile --name os launch.py --noconsole

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os == 'Windows' && 'windows-x64' || (runner.os == 'macOS' && 'macos-arm64' || 'linux-x64') }}
          path: dist/os${{ runner.os == 'Windows' && '.exe' || '' }}