name: Upload ResourcePack

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  upload-resourcepack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository with LFS
        uses: actions/checkout@v3
        with:
          lfs: true
      
      - name: Upload resourcepack as artifact
        uses: actions/upload-artifact@v3
        with:
          name: resourcepack
          path: resourcepack.zip
          if-no-files-found: error 